name: CI
on:
  workflow_dispatch:
  repository_dispatch:
    types: [strapi_updated,database_updated]
  push:
    branches:
      - master

jobs:
  build:
    concurrency: 
      group:  deploy-site
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Caching
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - run: yarn install
      - run: yarn run patch-package
      - run: yarn run build --log-pages
        env:
            CI: true
            STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
            STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
            GATSBY_DB_USER: ${{ secrets.GATSBY_DB_USER }}
            GATSBY_DB_PASS: ${{ secrets.GATSBY_DB_PASS }}
            GATSBY_DB_HOST: ${{ secrets.GATSBY_DB_HOST }}
            GATSBY_DB_PORT: ${{ secrets.GATSBY_DB_PORT }}
            GATSBY_DB_NAME: ${{ secrets.GATSBY_DB_NAME }}
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/36109138678/locations/global/workloadIdentityPools/estuary-marketing-pool/providers/estuary-marketing-provider'
          service_account: 'estuary-marketing-ci-cd@estuary-marketing.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 422.0.0'
      - name: Sync build folder
        run: "gsutil -q -m rsync -r ${{ github.workspace }}/public gs://estuary-marketing"
      - name: Set cache control on HTML files
        run: "gsutil -q -m setmeta -h 'cache-control: public, max-age=0, must-revalidate' 'gs://estuary-marketing/**/*.html' 'gs://estuary-marketing/**/*.json'"
      - name: Set cache control on js assets
        run: "gsutil -q -m setmeta -h 'cache-control: public, max-age=31536000, immutable' 'gs://estuary-marketing/**/*.js'"
      - name: Set cache control on svg assets
        run: "gsutil -q -m setmeta -h 'cache-control: public, max-age=31536000, immutable' 'gs://estuary-marketing/**/*.svg'"
      - name: Set cache control on png assets
        run: "gsutil -q -m setmeta -h 'cache-control: public, max-age=31536000, immutable' 'gs://estuary-marketing/**/*.png'"
      - name: Set cache control on webp assets
        run: "gsutil -q -m setmeta -h 'cache-control: public, max-age=31536000, immutable' 'gs://estuary-marketing/**/*.webp'"
      - name: Set cache control on static assets
        run: "gsutil -q -m setmeta -h 'cache-control: public, max-age=31536000, immutable' 'gs://estuary-marketing/static**/*'"
      - name: Invalidate cache
        if: success()
        run: "gcloud compute url-maps invalidate-cdn-cache estuary-marketing-new --path='/*' --async"